### ISSUE TITLE
Class alloc bug?

### ISSUE THREAD

**Issue by haifenghuang** [jdolan/Objectively#9]
In `Class.c`, the function `_alloc` has below statements:

    ident interface = clazz->interface;
    do {
        *(ident *) (obj + clazz->interfaceOffset) = interface;
    } while ((clazz = clazz->superclass));

But i think the first statement should be placed inside the `do` loop, like below:

    do {
        ident interface = clazz->interface;
        *(ident *) (obj + clazz->interfaceOffset) = interface;
    } while ((clazz = clazz->superclass));

am I right?

**Comment by jdolan** [comment]
Nope, I wrestled with those 3 lines for an hour one night :)

What this is actually doing, is making sure that every `interface` pointer within `obj` (and there is one for each class in its type hierarchy) points to `clazz->interface`. This is how, for example, an instance of `Array` receives `Array`'s implementation of `Object#dealloc`. It's difficult to follow, but it's correct -- I think ;)

For a non-trivial example of the inheritance this allows, take a look at [ObjectivelyMVC](https://github.com/jdolan/ObjectivelyMVC) and some of the Control classes included with it.

I'll leave this open in case I've misunderstood you. And thanks for your interest in the project!

**Comment by haifenghuang** [comment]
I see, thanks very much for the explanation, and also thanks for the great library, I learned a lot from the library code.

**Comment by jdolan** [comment]
You're welcome, and sure, go right ahead. If you have any interest in contributing to the project in the future, please reach out. The next major milestone is a general release with OS X, Linux and Windows support (MinGW only) for both Objectively and ObjectivelyMVC.
